name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2, 8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, json

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest
          echo "Composer install completed with exit code: $?"

      - name: Debug vendor directory
        run: |
          echo "Contents of vendor/bin:"
          ls -la vendor/bin/ || echo "vendor/bin directory not found"
          echo "PHPUnit executable check:"
          ls -la vendor/bin/phpunit || echo "PHPUnit not found"

      - name: Run code style checks
        run: |
          if [ -f "./vendor/bin/php-cs-fixer" ]; then
            ./vendor/bin/php-cs-fixer fix --dry-run --diff
          else
            echo "PHP CS Fixer not installed, skipping code style check"
          fi

      - name: Run static analysis
        run: |
          if [ -f "./vendor/bin/phpstan" ]; then
            ./vendor/bin/phpstan analyse
          else
            echo "PHPStan not installed, skipping static analysis"
          fi

      - name: Run tests
        run: |
          if [ -f "./vendor/bin/phpunit" ]; then
            ./vendor/bin/phpunit
          else
            echo "PHPUnit not found, trying alternative methods..."
            composer exec phpunit || php vendor/phpunit/phpunit/phpunit
          fi

  validate:
    name: Validate Package
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, json

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Validate autoloading
        run: composer dump-autoload --optimize --strict-psr

      - name: Check package syntax
        run: find src -name "*.php" -exec php -l {} \;

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run security audit
        run: |
          if [ -f "./vendor/bin/security-checker" ]; then
            ./vendor/bin/security-checker security:check
          else
            echo "Security checker not installed, skipping security audit"
          fi
